name: Deploy Synapse UAT to Prod

on:
  workflow_dispatch:
  push:
    branches:
      - workspace_publish

jobs:
  deploy:
    name: Deploy ARM templates to Prod
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CLIENT_SECRET }}
          
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: workspace_publish

      - name: Deploy Synapse to PROD
        uses: azure/arm-deploy@v2
        with:
          operation: 'deploy'
          TargetWorkspaceName: 'dfprodws'                         # NOT WorkspaceName
          TemplateFile: './workspace_publish/TemplateForWorkspace.json'
          ParametersFile: './workspace_publish/TemplateParametersForWorkspace.json'
          environment: 'Azure Public'
          resourceGroupName: "dftest_rg"
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}    # casing as in docs
          clientId: ${{ secrets.AZURE_CLIENT_ID }}                    # NOT ServicePrincipalId
          clientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}               # NOT ServicePrincipalKey
          tenantId: ${{ secrets.AZURE_TENANT_ID }}
