name: Deploy Synapse UAT to Prod

on:
  workflow_dispatch:
  push:
    branches:
      - workspace_publish

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: workspace_publish

      - name: Deploy Synapse to PROD
        uses: azure/arm-deploy@v2

      - uses: Azure/synapse-workspace-deployment@v2
        with:
          TargetWorkspaceName: 'dfprodws'
          TemplateFile: 'dfuatws/Custom_ARM_Template.json'
          ParametersFile: './params.json'
          operation: 'deploy'

